fixed lint compile time errors
camerongillette/factorio_blueprint_editor pull request #37
Opened 2017-11-28 01:57 UTC by lessthantrue

When I pulled in a fresh copy of the new master branch after lint was added, I got a lot of compiler errors. If anyone else is dealing with those, this should fix them.

2017-11-28 04:59 UTC, Zeragamba requested changes

2017-11-28 04:59 UTC, SpyMaster356 commented on js/script.js
> +        var u = decodeURIComponent;
Would be nice to have something a bit more descriptive the "o", "u", and "i"

2017-11-28 04:59 UTC, SpyMaster356 commented on js/script.js
> +window['savebtn'] = function () {
`window.savebtn` would work here as well

2017-11-28 04:59 UTC, SpyMaster356 commented on js/script.js
> +function closebtn() {
I think this is used from the html. If it is it should be added to the window obiect.

2017-11-28 10:32 UTC, Zeragamba approved these changes

2017-11-29 12:35 UTC, SpyMaster356 commented
@lessthantrue can you push a new commit (edit the README or something) to trigger a Travis build?

2017-11-29 13:25 UTC, SpyMaster356 commented
[fixes #40]

2017-11-29 13:27 UTC, merged