Inserter upside down rotate fix.
camerongillette/factorio_blueprint_editor pull request #38
Opened 2017-11-28 03:07 UTC by camerongillette

Changes
-Logic to handle mirroring by adding additional/optional parameter to placeable variable
-Code cleanup
-Logging cleanup
-Wrote basic documentation on contents of placeable array contents

Testing Instructions
-Add inserter of any type and rotate. The inserter should know rotate instead of flip upside down.

2017-11-28 05:05 UTC, Zeragamba requested changes

2017-11-28 05:05 UTC, SpyMaster356 commented on js/script.js
>  var placeable = [
We should break this out into a json file later.

2017-11-28 05:05 UTC, SpyMaster356 commented on js/script.js
> +        console.log('Direction Start' + dirStart);
I think we should remove debugging console logs from the code.

2017-11-28 05:05 UTC, SpyMaster356 commented on js/script.js
> +    createPreview(this.dataset.url, this.dataset.r, this.dataset.direction, this.dataset.w, this.dataset.h, this.dataset.mirrorFlippedHorizontal);
Seems like this method uses a lot of values from dataset. It might be easier to pass the dataset object it's self

2017-11-29 03:17 UTC, camerongillette commented
@SpyMaster356 Ready for re-review

2017-11-29 12:31 UTC, SpyMaster356 commented
@camerongillette can you push a new commit (edit the README or something) to trigger a Travis build?

2017-11-29 12:31 UTC, Zeragamba approved these changes

2017-11-29 13:39 UTC, SpyMaster356 commented
actually, looks like closing and reopening works a well

2017-11-29 13:42 UTC, Zeragamba requested changes

2017-11-29 13:42 UTC, SpyMaster356 commented on js/script.js
> +    } else if (!isBlocked(previewdiv.dataset.name, this.dataset.x, this.dataset.y, )) {
Got an extra tailing comma here

2017-11-30 02:14 UTC, camerongillette commented
@SpyMaster356 Ready for re-review.

2017-12-01 12:19 UTC, Zeragamba approved these changes

2017-12-01 12:19 UTC, merged